name: studip
description: A simple-to-use wrapper for Stud.IP's RestAPI service in Dart.
version: 3.0.0-alpha.0
homepage: https://github.com/ThexXTURBOXx/dart-studip
repository: https://github.com/ThexXTURBOXx/dart-studip
issue_tracker: https://github.com/ThexXTURBOXx/dart-studip/issues
funding:
  - https://github.com/sponsors/ThexXTURBOXx
topics:
  - rest
  - studip
  - web

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  http: ^1.1.0
  oauth2_client: ^3.2.2

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  oauth2_client:
    git:
      url: https://github.com/ThexXTURBOXx/oauth2_client.git
