name: studip
description: A simple-to-use wrapper for Stud.IP's RestAPI service in Dart.
version: 2.1.3
homepage: https://github.com/ThexXTURBOXx/dart-studip
repository: https://github.com/ThexXTURBOXx/dart-studip
issue_tracker: https://github.com/ThexXTURBOXx/dart-studip/issues
funding:
  - https://github.com/sponsors/ThexXTURBOXx
topics:
  - rest
  - studip
  - web

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  http: '>=0.13.3 <2.0.0'
  oauth1: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
