name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Pana
        run: flutter pub global activate pana

      - name: Get dependencies
        run: flutter pub get

      - name: Lint
        run: dart format -o none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze

      - name: Pana
        run: pana
